# Generated by Django 5.0 on 2024-04-15 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_client_delete_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
