# Generated by Django 5.0 on 2024-04-15 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_remove_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='message_type',
            field=models.CharField(choices=[('fire', 'Forest Fire Alert'), ('heat', 'Heat Warning'), ('custom', 'Custom Message')], default='custom', max_length=10),
        ),
        migrations.AlterField(
            model_name='client',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
