# Generated by Django 5.0 on 2024-04-15 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_client_message_type_alter_client_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='message',
        ),
    ]
