# Generated by Django 5.0 on 2024-04-15 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_remove_client_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='message_type',
            field=models.CharField(choices=[('fire', 'Forest Fire Alert'), ('heat', 'Heat Warning')], default='fire', max_length=10),
        ),
    ]
