# Generated by Django 5.0 on 2024-04-15 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_alter_client_message_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='message_type',
            field=models.CharField(choices=[('rain', 'Digniin Roobab Culus: Waxaa la saadaalinayaa roobab culus oo ka da’aya deegaanka. Fadlan ka fogow meelaha biyuhu maraan iyo daadadka, iskana ilaali safarka aan loo baahnayn. Hubso inaad haysato agabkaaga gurmadka haddii loo baahdo'), ('heat', 'Digniin Cimilo Kulul: Waxaa la filayaa in heer kulku si aad ah u kordho maalmaha soo socda. Fadlan iska ilaali qorraxda tooska ah inta u dhexeysa 10ka subaxnimo ilaa 4ta galabnimo, cab biyo badan, oo xiro dhar fudud oo hawo leh')], default='fire', max_length=10),
        ),
    ]
