# Generated by Django 5.0 on 2024-04-10 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fullname', models.CharField(max_length=120)),
                ('Location', models.CharField(max_length=120)),
                ('Phone', models.CharField(max_length=120)),
                ('Password', models.CharField(max_length=120)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20)),
            ],
        ),
    ]
